/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lost.macpan;

import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;
// wird später implementiert
class AppTest {

}
